### ISSUE TITLE
some premature thoughts on the impl

### ISSUE THREAD

**Issue by haolian9** [letstakeawalk/fugitive-ext.nvim#1]
hi! i just skimmed the code, i like the way how it extends fugitive, and i personally like its coding style. 
yet, i hope you dont mind, IMHO there are some potential improvements:
* `actions.confirm_action()` calls `vim.ui.input` instead of `vim.ui.select`. based on my past experience,  i feel .select would be more handy, as it does not requires pressing `return`, while .input requires input sequences like `y<cr>`.
* `feed_escaped_keys` instead of `vim.fn.maparg`. i am not sure about it, as i have not tested this plugin + fugitive, i just think it would be more reliable that storing the fugitive specific keymaps before fugitive-ext.nvim remapping its own ones, and then call the fugitive-specic one based on the retun value of maparg.

**Comment by letstakeawalk** [comment]
Thank you for sharing your thoughts.

I have also considered making the confirmation prompt with `vim.ui.select`. Personally, I prefer `vim.ui.input` because it's easy to mistype when making a selection. Plus, if you use a custom ui interface like [dressing.nvim](https://github.com/stevearc/dressing.nvim), you would still have to type `1<CR>` to confirm the selection anyway. I favor the explicitness of typing `y<CR>` over numbered choices.
That being said, I will consider adding an option to choose between `input`(default) and `select` for enhanced customizability.

Could you please elaborate on what you meant by the second bullet point?

**Comment by haolian9** [comment]
> if you use a custom ui interface like [dressing.nvim](https://github.com/stevearc/dressing.nvim), you would still have to type 1<CR> to confirm the selection anyway.

oh, sorry. i have a custom vim.ui.select which works like [this](https://user-images.githubusercontent.com/6236829/238661875-d5beeca6-fe16-44aa-9f8c-dcf4923d5235.mp4), but it has no difference as default between .input and .select indeed.

> the use of maparg

it's also an invalid pointer.
```lua
--https://github.com/bharam/fugitive-ext.nvim/blob/029716f90026283fc2aa61a009504ba0a46fa5b5/lua/fugitive-ext/actions.lua#L134
Actions.discard             = "<Plug>fugitive:X"  -- Discard changes
...
Actions.discard_confirm = confirm_action(Actions.discard, "Are you sure to discard changes? (y/n)")
```
`maparg('X', 'n', false, true)` will return this `"<Plug>fugitive:X"`, but i was blind to above definition, so there is no need to call it explicitly.

it turns out my thoughts are all noises, sorry to open this issue.
